version: "2"
linters:
  default: all
  disable:
    - ireturn
    - nlreturn
    - revive # for tests only
    - varnamelen
    - wsl
  settings:
    depguard:
      rules:
        main:
          allow:
            - github.com/michurin/tc
            - github.com/davecgh/go-spew/spew
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/michurin/tc)
