version: "2"
linters:
  default: all
  disable:
    - ireturn
    - nlreturn
    - varnamelen
    - wsl
  settings:
    depguard:
      rules:
        tests:
          files:
            - $test
          allow:
            - github.com/michurin/tc
            - github.com/davecgh/go-spew/spew
  exclusions:
    warn-unused: true
    rules:
      - path: _test.go
        linters:
          - revive
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/michurin/tc)
