---
name: build # this string appears on badge
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: "Go ${{ matrix.go }} tests"
    strategy:
      matrix:
        go:
          - "1.21"
          - "1.22"
          - "1.23"
          - "1.24"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ matrix.go }}"
      - run: "go version"
      - run: "go test ."
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: "Linting"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - uses: golangci/golangci-lint-action@v7
        with:
          version: "v2.1.2"
  codecov:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: "Code coverage"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - run: "go test -v -coverprofile=coverage.txt -covermode=atomic ."
      - uses: codecov/codecov-action@v5
        with:
          files: ./coverage.txt
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }} # required
